sus = 0;
mxesus = 0;
mxepart = true;
textpart = false;
intropart = false;
text_amount = 0;
image_alpha = 1;
text[0] = "";
text[1] = "This Game Was Presented to you by JohnMX and Cueio77";
text[2] = "the ONE and ONLY";
//global.song = "Tough Guy Alert";
textpart = true;
audio_play_sound(MxStart6, 0, 0);