global.loaded_mod = "mainfiles";
global.song = "MegaX";
sprite_index = sprite_add(string(global.loaded_mod)+"/spr_songbox.png", 1, false, false, 0, 64);
global.note_left_held = sprite_add(string(global.loaded_mod)+"/spr_doublenotes_left.png", 4, false, false, 32, 32);
global.note_right_held = sprite_add(string(global.loaded_mod)+"/spr_doublenotes_right.png", 4, false, false, 32, 32);
global.note_up_held = sprite_add(string(global.loaded_mod)+"/spr_doublenotes_up.png", 4, false, false, 32, 32);
global.note_down_held = sprite_add(string(global.loaded_mod)+"/spr_doublenotes_down.png", 4, false, false, 32, 32);
global.note_sprite = sprite_add(string(global.loaded_mod)+"/spr_notes_normal.png", 4, false, false, 32, 32);
global.held_notes_sprite = sprite_add(string(global.loaded_mod)+"/spr_longnotes.png", 3, false, false, 32, 32);
global.inputs_and_event = sprite_add(string(global.loaded_mod)+"/spr_inputs.png", 6, false, false, 32, 32);
var scl = sprite_nineslice_create();

application_surface_draw_enable(true);
scl.enabled = true;
scl.left = 32;
scl.right = 32;
scl.top = 32;
scl.bottom = 32;
scl.tilemode[nineslice_left] = nineslice_mirror;
scl.tilemode[nineslice_right] = nineslice_mirror;
scl.tilemode[nineslice_top] = nineslice_mirror;
scl.tilemode[nineslice_bottom] = nineslice_mirror;
scl.tilemode[nineslice_center] = nineslice_mirror;

sprite_set_nineslice(sprite_index, scl);
image_txscale = 1000;
image_tyscale = 2;
image_xscale = 0;
image_yscale = 0;

global.song_started = false;
pause = false;
Before_Song();
sus = 0;
sas = 0;
played = false;
talk = audio_create_stream(talk_place);

ccnt = 0;
ccntx = 0;
cnt[0] = 1;
cnt[1] = 1;
cnt[2] = 1;
cnt[3] = 1;
cnt[4] = 1;
cnt1[0] = 0;
cnt1[1] = 0;
cnt1[2] = 0;
cnt1[3] = 0;
cnt1[4] = 0;
countdown_sprite = sprite_add("mainfiles/spr_introcount.png", 6, false, false, 32, 32);
countdown_sprite_bright = sprite_add("mainfiles/spr_introcount_bright.png", 5, false, false, 32, 32);
s = 0;
global.countdown = false;
start_time = current_time;
scroll_speed = 1.2;
saved_x = xstart;